In [13]:
# !pip install kagglehub
import pandas as pd

In [14]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rabieelkharoua/students-performance-dataset")

print("Path to dataset files:", path)

Path to dataset files: /Users/alismac/.cache/kagglehub/datasets/rabieelkharoua/students-performance-dataset/versions/2

In [15]:
%ls  /Users/alismac/.cache/kagglehub/datasets/rabieelkharoua/students-performance-dataset/versions/2

Student_performance_data _.csv

In [16]:
path = '/Users/alismac/.cache/kagglehub/datasets/rabieelkharoua/students-performance-dataset/versions/2/Student_performance_data _.csv'

In [17]:
studentsdf = pd.read_csv(path)

In [18]:
studentsdf.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [19]:
studentsdf.head(-5)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2382,3383,16,0,0,3,13.941823,20,0,2,0,0,0,0,1.191929,3.0
2383,3384,16,1,2,2,11.736409,18,1,4,0,0,0,0,1.810038,3.0
2384,3385,15,1,0,1,16.655581,13,1,3,0,1,0,0,2.539113,4.0
2385,3386,16,1,0,1,1.445434,20,0,3,1,1,0,0,1.395631,1.0
2386,3387,16,0,0,2,13.814021,14,0,2,0,0,0,0,2.000084,4.0

In [20]:
studentsdf.shape

(2392, 15)

In [22]:
studentsdf.describe

<bound method NDFrame.describe of       StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0          1001   17       1          0                  2        19.833723
1          1002   18       0          0                  1        15.408756
2          1003   15       0          2                  3         4.210570
3          1004   17       1          0                  3        10.028829
4          1005   17       1          0                  2         4.672495
...         ...  ...     ...        ...                ...              ...
2387       3388   18       1          0                  3        10.680555
2388       3389   17       0          0                  1         7.583217
2389       3390   16       1          0                  2         6.805500
2390       3391   16       1          1                  0        12.416653
2391       3392   16       1          0                  2        17.819907

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0            7         1                2                0       0      1
1            0         0                1                0       0      0
2           26         0                2                0       0      0
3           14         0                3                1       0      0
4           17         1                3                0       0      0
...        ...       ...              ...              ...     ...    ...
2387         2         0                4                1       0      0
2388         4         1                4                0       1      0
2389        20         0                2                0       0      0
2390        17         0                2                0       1      1
2391        13         0                2                0       0      0

      Volunteering       GPA  GradeClass
0                0  2.929196         2.0
1                0  3.042915         1.0
2                0  0.112602         4.0
3                0  2.054218         3.0
4                0  1.288061         4.0
...            ...       ...         ...
2387             0  3.455509         0.0
2388             0  3.279150         4.0
2389             1  1.142333         2.0
2390             0  1.803297         1.0
2391             1  2.140014         1.0

[2392 rows x 15 columns]>

In [24]:
tutor = studentsdf[studentsdf['Tutoring']==1]
no_tutor = studentsdf[studentsdf['Tutoring']==0]

In [25]:
tutor.describe

<bound method NDFrame.describe of       StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0          1001   17       1          0                  2        19.833723
4          1005   17       1          0                  2         4.672495
7          1008   15       1          1                  4        15.424496
14         1015   18       1          0                  1        11.197811
15         1016   15       0          0                  2         9.728101
...         ...  ...     ...        ...                ...              ...
2374       3375   16       0          2                  1         2.313504
2377       3378   18       0          0                  2        12.749976
2383       3384   16       1          2                  2        11.736409
2384       3385   15       1          0                  1        16.655581
2388       3389   17       0          0                  1         7.583217

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0            7         1                2                0       0      1
4           17         1                3                0       0      0
7           22         1                1                1       0      0
14           9         1                2                0       0      0
15          17         1                0                0       1      0
...        ...       ...              ...              ...     ...    ...
2374         5         1                3                1       0      0
2377         8         1                0                1       1      0
2383        18         1                4                0       0      0
2384        13         1                3                0       1      0
2388         4         1                4                0       1      0

      Volunteering       GPA  GradeClass
0                0  2.929196         2.0
4                0  1.288061         4.0
7                0  1.360143         4.0
14               0  2.396788         3.0
15               0  1.341521         4.0
...            ...       ...         ...
2374             0  2.913898         0.0
2377             0  2.652355         2.0
2383             0  1.810038         3.0
2384             0  2.539113         4.0
2388             0  3.279150         4.0

[721 rows x 15 columns]>

In [27]:
no_tutor.describe

<bound method NDFrame.describe of       StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
1          1002   18       0          0                  1        15.408756
2          1003   15       0          2                  3         4.210570
3          1004   17       1          0                  3        10.028829
5          1006   18       0          0                  1         8.191219
6          1007   15       0          1                  1        15.601680
...         ...  ...     ...        ...                ...              ...
2386       3387   16       0          0                  2        13.814021
2387       3388   18       1          0                  3        10.680555
2389       3390   16       1          0                  2         6.805500
2390       3391   16       1          1                  0        12.416653
2391       3392   16       1          0                  2        17.819907

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
1            0         0                1                0       0      0
2           26         0                2                0       0      0
3           14         0                3                1       0      0
5            0         0                1                1       0      0
6           10         0                3                0       1      0
...        ...       ...              ...              ...     ...    ...
2386        14         0                2                0       0      0
2387         2         0                4                1       0      0
2389        20         0                2                0       0      0
2390        17         0                2                0       1      1
2391        13         0                2                0       0      0

      Volunteering       GPA  GradeClass
1                0  3.042915         1.0
2                0  0.112602         4.0
3                0  2.054218         3.0
5                0  3.084184         1.0
6                0  2.748237         2.0
...            ...       ...         ...
2386             0  2.000084         4.0
2387             0  3.455509         0.0
2389             1  1.142333         2.0
2390             0  1.803297         1.0
2391             1  2.140014         1.0

[1671 rows x 15 columns]>

In [28]:
tutor_sample = tutor.sample(100)
no_tutor_sample = no_tutor.sample(100)

In [29]:
from scipy.stats import stats

In [36]:
ttest, pval = stats.ttest_ind(tutor_sample['GradeClass'], no_tutor_sample['GradeClass'], equal_var= False)

/var/folders/45/9szzk0kd6w1152nswdn8m3fh0000gn/T/ipykernel_13434/1814455190.py:1: DeprecationWarning: Please import `ttest_ind` from the `scipy.stats` namespace; the `scipy.stats.stats` namespace is deprecated and will be removed in SciPy 2.0.0.
  ttest, pval = stats.ttest_ind(tutor_sample['GradeClass'], no_tutor_sample['GradeClass'], equal_var= False)

In [37]:
pval

np.float64(0.08681162588255817)

# - H_null= totoring and non tutoring students hava same marks
# - H_alt = tutoring and non tutoring students does not have same marks

In [38]:
if pval < 0.05:
    print('Reject null hypothesis')

else:
    print(' Failed to reject null Hypothesis')

 Failed to reject null Hypothesis